# Generated by Django 3.1.7 on 2021-04-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='times_played',
            field=models.IntegerField(),
        ),
    ]
