# Generated by Django 3.1.7 on 2021-04-22 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists_api', '0002_auto_20210421_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='artists',
            new_name='artist',
        ),
    ]
