# Generated by Django 3.1.7 on 2021-04-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists_api', '0004_auto_20210422_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='self_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='tracks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='self_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
